### PR TITLE
Add support for .Include after .Rewrite

### LINKED ISSUE #11: NotSupportedException when using DbInjectable within a sub query
Hi,

A NotSupportedException is thrown by EF6 when trying to use .Any() on a DbInjectable query.

I have a query like this:
```
var foo = dbContext.Set<Foo>().ToDbInjectable();
var query = from bar in dbContext.Set<Bar>()
            where foo.Any(f => f.SomeInjectLambdaMethod())
            select bar;
```

Now it doesn't even have to contain method that should be replaced with a lambda, only the .ToDbInjectable() is enough to get the exception.

This can be simply reproduced in the following test:
NeinLinq.Tests.DbAsyncQuery.RealTest
```
[Fact]
public async Task AnyShouldSucceed()
{
    var rewriter = new Rewriter();

    var dummies = db.Dummies.ToDbInjectable();
    var query = from dummy in db.Dummies
                where dummies.Any(d => d.Id < dummy.Id)
                select dummy;
    
    var result = await query.ToListAsync();

    Assert.True(rewriter.VisitCalled);
    Assert.Equal(2, result.Count);
}
```

Full stack:
```
System.NotSupportedException
A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.
   at System.Data.Entity.Internal.ThrowingMonitor.EnsureNotEntered()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at NeinLinq.RewriteQueryable`1.GetEnumerator() in C:\Users\Johannes\Source\nein-linq\src\NeinLinq.Queryable\RewriteQueryable.cs:line 37
   at NeinLinq.RewriteQueryable`1.System.Collections.IEnumerable.GetEnumerator() in C:\Users\Johannes\Source\nein-linq\src\NeinLinq.Queryable\RewriteQueryable.cs:line 41
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.ConstantTranslator.TypedTranslate(ExpressionConverter parent, ConstantExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, DbExpression& source, DbExpressionBinding& sourceBinding, DbExpression& lambda)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, DbExpression& source, DbExpressionBinding& sourceBinding, DbExpression& lambda)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.Convert()
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClassc.<GetResultsAsync>b__a()
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__3d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<ExecuteAsyncImplementation>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<GetResultsAsync>d__e.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.<FirstMoveNextAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<ForEachAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NeinLinq.Tests.DbAsyncQuery.RealTest.<AnyShouldSucceed>d__8.MoveNext() in C:\Users\Johannes\Source\nein-linq\test\NeinLinq.Tests\DbAsyncQuery\RealTest.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext()
```

### PR DESCRIPTION
**Pull request by axelheer**
This adds some workarounds for Entity Framework and Entity Framework Core Queries, which contain .Include calls after some .Rewrite call. Both seem to handle these calls quite special. 😷

* Entity Framework calls an .Include method of the underlying queryable using reflection instead of adding an .Include call to the query chain
* Entity Framework Core adds an .Include call to the query chain, but only if the query provider of the underlying queryable is the internal query provider provided by Entity Framework Core

Fixes #11 (finally)

cc @jhartmann123 @peterwurzinger

### CODE REVIEW

**Comment by peterwurzinger** [comment]
I'm craving for a facepalm reaction on another episode of EF query madness. Both implementations are ridiculous, imho.

**Comment by axelheer** [comment]
I can handle the Reflection Madness of Entity Framework (I've just to add those methods too), but inheriting the internal query provider of Entity Framework Core just to make it work stinks a lot...

**Comment by jhartmann123** [comment]
I hate to be annoying, but with this branch I can't get sub queries with includes to work at all.

I've hacked down some basic tests (see below) trying out various combinations of .ToDbInjectable(). While it is obvious that RewriteInlcudeSub1 and RewriteSub1 fail, to me as a user it is not entirely clear why the others fail. And for subqueries + include I couldn't find any working combination.

```cs
public static class TestRewrites
{
    [InjectLambda]
    public static bool MaxId(this Dummy dummy, int maxId) => throw new NotImplementedException();

    public static Expression<Func<Dummy, int, bool>> MaxId() => (dummy, maxId) => dummy.Id <= maxId;
}
```

DbAsyncQuery.RealTest:
```cs
[WindowsFact]
public async Task RewriteSub1()
{
    var dummies = db.Dummies;
    var query = from d in db.Dummies
                where dummies.Any(d2 => d2.MaxId(d.Id))
                select d;

    var result = await query.ToListAsync();
}

[WindowsFact]
public async Task RewriteSub2()
{
    var dummies = db.Dummies;
    var query = from d in db.Dummies
                where dummies.ToDbInjectable().Any(d2 => d2.MaxId(d.Id))
                select d;

    var result = await query.ToListAsync();
}

[WindowsFact]
public async Task RewriteSub3()
{
    var dummies = db.Dummies.ToDbInjectable();
    var query = from d in db.Dummies
                where dummies.Any(d2 => d2.MaxId(d.Id))
                select d;

    var result = await query.ToListAsync();
}

[WindowsFact]
public async Task RewriteSub4()
{
    var dummies = db.Dummies;
    var query = from d in db.Dummies
                where dummies.Any(d2 => d2.MaxId(d.Id))
                select d;

    var result = await query.ToDbInjectable().ToListAsync();
}

[WindowsFact]
public async Task RewriteSub5()
{
    var dummies = db.Dummies;
    var query = from d in db.Dummies
                where dummies.ToDbInjectable().Any(d2 => d2.MaxId(d.Id))
                select d;

    var result = await query.ToDbInjectable().ToListAsync();
}

[WindowsFact]
public async Task RewriteIncludeSub1()
{
    var dummies = db.Dummies;
    var query = from d in db.Dummies
                where dummies.Any(d2 => d2.MaxId(d.Id))
                select d;

    var result = await query.Include(d => d.Other).ToListAsync();
}

[WindowsFact]
public async Task RewriteIncludeSub2()
{
    var dummies = db.Dummies;
    var query = from d in db.Dummies
                where dummies.ToDbInjectable().Any(d2 => d2.MaxId(d.Id))
                select d;

    var result = await query.Include(d => d.Other).ToListAsync();
}

[WindowsFact]
public async Task RewriteIncludeSub3()
{
    var dummies = db.Dummies.ToDbInjectable();
    var query = from d in db.Dummies
                where dummies.Any(d2 => d2.MaxId(d.Id))
                select d;

    var result = await query.Include(d => d.Other).ToListAsync();
}

[WindowsFact]
public async Task RewriteIncludeSub4()
{
    var dummies = db.Dummies;
    var query = from d in db.Dummies
                where dummies.Any(d2 => d2.MaxId(d.Id))
                select d;

    var result = await query.ToDbInjectable().Include(d => d.Other).ToListAsync();
}

[WindowsFact]
public async Task RewriteIncludeSub5()
{
    var dummies = db.Dummies;
    var query = from d in db.Dummies
                where dummies.Any(d2 => d2.MaxId(d.Id))
                select d;

    var result = await query.Include(d => d.Other).ToDbInjectable().ToListAsync();
}
```

**Comment by jhartmann123** [comment]
Just to leave my unprofessional opinion here: I don't have any real benifit from a .ToDbInjectable() with a own query type like RewriteQuery. I'm perfectly fine with having a well defined point in my code where my query expression gets rewritten, like in the .Rewrite()-extension I've posted in #11.

The only benifit we'd have in our application is that we could do something like `db.Dummies.ToDbInjectable().Any(d => d.MaxId())`, but I happily trade that against the more stable `db.Dummies.Where(d => d.MaxId()).Rewrite().Any()`.

**Comment by axelheer** [comment]
I‘m currently sick and will have a look on your tests when I’m fit again.

Based on your feedback we‘ve already got two improvements for this library. I don‘t would call that annoying.

**Comment by axelheer** [comment]
* RewriteSub1
  * Cannot work w/o rewrite
* RewriteSub2
  * The call to `ToDbInjectable` happens within the LINQ query
  * Thus, Enity Framework tries to translate `ToDbInjectable` (not possible)
* RewriteSub3
  * The outer query has no rewrite
  * Thus, the rewrite of the inner query cannot be resolved
* RewriteSub4
  * works in my branch!
* RewriteSub5
  * see RewriteSub2 (although the error message is quite strange here)
* RewriteIncludeSub1
  * see RewriteSub1
* RewriteIncludeSub2
  * RewriteSub2
* RewriteIncludeSub3
  * see RewriteSub3
* RewriteIncludeSub4
  * works in my branch!
* RewriteIncludeSub5
  * see RewriteSub2

Further discussion of other constellations in #11 please. These changes seem to help anyway.

**Comment by MartinJohns** [comment]
This unfortunately does not seem to support `Include(x => x...).ThenInclude(x => x...)` yet.

**Comment by axelheer** [comment]
@MartinJohns can you pls file an issue?

**Comment by MartinJohns** [comment]
Yeah, sure, I was just thinking out loud while I'm still looking at the issue. :-)

**Pull request merged**
