### PR TITLE
Add cached expression

### PR DESCRIPTION
**Pull request by axelheer**
cc @peterwurzinger

### CODE REVIEW

**Comment by peterwurzinger** [comment]
Looks good to me - the idea of overloading the cast is really cool.

I would suggest allowing to create a cache by an expression-returning method as a second way. There are two main benefits that I'd see from that:
1. There is a migration-path from the "old" way of using NeinLinq, basically all you have to do is pass the expression-method to the cache and use it in the delegate.
2. More sophisticated expressions will be more readable when implemented in their own methods, instead of the cache factory.

**Comment by axelheer** [comment]
Shouldn’t `ExpressionCache.From(OldOrFancyMethod())` do it?

**Comment by peterwurzinger** [comment]
I think you cannot call non-static methods in a field initializer or a constructor.

**Comment by axelheer** [comment]
Yes, you can - use the constructor ✊

**Comment by peterwurzinger** [comment]
Yeah, just realized that you can actually do that in a constructor. I'll write it on my "Facts about C# I didn't want to know"-list...

The question then is, is it wise to do that? An expression-returning method might depend on the state of the object it is contained in. Calling that method instead of passing its reference for later use might often result in temporal coupling between creation of the objects state and the cached expression:
```csharp
class Example
{
    CachedExpression<Func<int, string>> _cachedExpr;
    int j;

    Example()
    {
        CachedExpression<Func<int, string>> _cachedExpr = ExpressionCache.From(GetExpression());
        j = 5;
    }

    Expression<Func<int, string>> GetExpression()
    {
        return i => (i * j).ToString();
    }
} 
```

This is btw. applicable for every (cached) expression, that depends on state, not only the ones manufactured by a method.

**Comment by axelheer** [comment]
I don’t see a problem here, the expression still references Example.j, I think 💭

I should add an implicit operator for the other way round. That should come in handy.

**Comment by peterwurzinger** [comment]
When the expression-method is called `j` is uninitialized. I would be highly surprised if the result isn't `"0"` - therefore the cached Expression being
```csharp
i => (i * 0).ToString();
```

**Comment by axelheer** [comment]
Try it 😬

**Comment by peterwurzinger** [comment]
I better didn't. Starting another list "Facts about Lambda closures I didn't want to know"...

Jokes aside, seems like member variables are also getting captured by reference - even value types. What's now left are captured variables, that are getting evaluated outside of the closure:
```csharp
public class Example
{
    readonly CachedExpression<Func<int, string>> _cachedExpr;
    readonly int j;

    public Example()
    {
        _cachedExpr = CachedExpression.From(BlaExpr());
        j = 5;
    }

    //Returns "0"
    public string Bla(int i)
    {
        return _cachedExpr.Compiled(i);
    }

    Expression<Func<int, string>> BlaExpr()
    {
        //Evaluation outside the closure - ofc this doesn't make any sense.
        var k = j;
        return i => (i * k).ToString();
    }
}
```

I don't know if that is a thing or not.

**Comment by peterwurzinger** [comment]
One last thing, what are your thoughts on automatically translating calls to `Compiled` to `Expression` in an injectable-query? Since you can *only* create a CachedExpression by a given Expression, I don't see use case other than providing Delegates for Expressions (and vice versa).
Use cases are private (but yet translate-worthy) expressions, that aren't exposed through a public API:

```csharp
public class EntityQuery<T, TKey>
    where TKey : IEquatable<TKey>
{
    private readonly IQueryable<T> entities;
    private readonly CachedExpression<Func<T, TKey>> keyExpr;

    public EntityQuery(IQueryable<T> entities, Expression<Func<T, TKey>> keySelector)
    {
        this.entities = entities;
        keyExpr = keySelector;
    }

    public T ByKey(TKey key)
    {
        var result = (from entity in entities

                        //Do magic here
                        let entityKey = keyExpr.Compiled(entity)

                        //I know, that there could still be problems translating .Equals()-calls in this example
                        where key.Equals(entityKey)
                        select entity).SingleOrDefault();
        return result;
    }
}
```

Currently you would still have to implement a separate method `TKey Key(T entity)` that gets decorated with `[InjectLambda]`.

**Comment by axelheer** [comment]
I think it would have more overhead, but I will try it in the evening or tomorrow.

**Comment by axelheer** [comment]
Oh, that would mean the query expression includes invocation expressions, which need some "fixes". That's not the road I want to hit...

Another approach would be replacing extension methods, which just call `.Compiled`, but then NeinLinq must provide all the extension methods for `Func<T1, ..., TN, TResult>` with super special treatment, because that would mean static methods injecting instance methods. That sucks.

Note: injecting instance stuff has the most overhead. Thus, if there is no "state", using static method or property injection is still the most efficient way to go.

I'd say this PR is done and ready. I'll sleep over the last translation idea. Maybe the day for finding a nice solution is not today.

**Pull request merged**
